### ISSUE TITLE
Linux Mint Issues

### ISSUE THREAD

**Issue by lorenzoi** [lokedhs/gnu-apl-mode#21]
Hello,
I recently downloaded gnu-apl-mode to emacs. When I try to do s-l a Cinnamon Debugger screen pops up, when I do s-e I get my file manager.
It would be nice if you included a way to change the APL key.
Thanks

**Comment by lorenzoi** [comment]
Also I don't have APL-Z

**Comment by lokedhs** [comment]
How did you install it? Did you use MELPA or did you clone the source?

**Comment by lokedhs** [comment]
Now that I read your message again, I now see what happened. Your problem is that your desktop steals the keypress before Emacs has a chance to see it. I solved that problem by removing all the shortcuts from GNOME that use the super key prefix.

That's the best solution, since the super prefix is really useful to have available in Emacs. If you really don't want to do that, then you can always customise the variable ‘gnu-apl-interactive-mode-map-prefix’ to use, say, hyper instead.
