### ISSUE TITLE
Proposal: Add to MELPA

### ISSUE THREAD

**Issue by Elzair** [lokedhs/gnu-apl-mode#9]
Would you add this package to [MELPA](http://melpa.org/#/)? Also, what is the license?

**Comment by lokedhs** [comment]
It was on MELPA, but now I can't see it on the package list. I don't know
what happened, to be honest.

The license for the C++ portion is GNU, since it's shipped together with
GNU APL itself. The Emacs part is BSD, although it'll change to GNU as well
once I get the copyright transfer documents in order so that I can
contribute it to ELPA.

**Comment by Elzair** [comment]
Cool! Thanks!

**Comment by mohammedtarek1** [comment]
I can see it in MELPA now :+1:

**Comment by lokedhs** [comment]
Yes, I noticed that too. It's a bit weird given that I haven't actually done anything. I wonder for how long the package was missing, and why it popped back up again.

**Comment by Elzair** [comment]
I am glad this has been resolved.
